project:
  id: e0120c86-c0ff-4548-9799-f58dfcffe7a7
  name: My-First-App
  location: eastus2
  environment: dev
  created: '2026-03-19T20:30:24.756256+00:00'
  iac_tool: terraform
naming:
  strategy: microsoft-alz
  org: ''
  env: dev
  zone_id: zd
ai:
  provider: azure-openai
  model: gpt-4o
  azure_openai:
    endpoint: ''
    deployment: gpt-4o
agents:
  custom_dir: .prototype/agents/
  custom: {}
  overrides: {}
deploy:
  track_changes: true
  subscription: ''
  resource_group: ''
  tenant: ''
  service_principal: ''
  generated_secrets: ''
backlog:
  provider: github
  org: ''
  project: ''
  token: ''
mcp:
  servers: ''
  custom_dir: .prototype/mcp/
stages:
  init:
    completed: true
    timestamp: '2026-03-19T20:30:24.764935+00:00'
  design:
    completed: false
    timestamp: null
    iterations: 0
  build:
    completed: false
    timestamp: null
  deploy:
    completed: false
    timestamp: null
